language: ruby
rvm:
- 2.4

install:
- bundle install

script: bundle exec rake site:deploy --quiet

env:
  global:
    secure: aYJvDWcSZ3u7dsdDDlNXeFXZnwqRSC2+DaNx0FdXVSKMcJOZ2Pfk8sV+EG+ob7XqggLB9poPi+bBqHhPg0PJJHH5oWqh0+EdlQ+rXfaTP8xAJ1mtZQLnNOSjJMEAKIJ6cowIexnzYA8zS7+yWq6glmUEfkQ1hVLrnisqhCrftKBBki/Gcf7Ql0NkC+ljkA4igPbVYiNP6lc1gp5fPwEya3LNAV5/JSaHSW7hKe1OzxEdpnmkgYMT/hBZGqp7qx4xrXbbvhenfrXoGmpw8eSQswcCVeA/QZwAmWW+jBbd0+bGnD5dkQCJDgDs1hvfY+tZ0Y890sz9r/7QSN0XQYtwusCZ38qYWmNCiWPZesoEj2BZXsD8zGzlxA3QAFDxUH6hxY3ABo2gWrORhr7P/MKi5mR5abiSLi2DfQOyG8Nj84PDAIsogIelRkMnywadg1JMM3PAvgRvTEHX/MjhpVAlLhELAGAdFfa01G7cGVz2uFIoi4MUnF8Th8KMTrcQssj14u/W/kabTRwgyQ7c6MzspNc5QlM+zFOP+qC9U4qOIk75J4VX46SzQ00nAoPTyEoLNAzeJH0Zjd1QUHOcDgv21Ttz7mnytjflbgisTE2xiTeJXj7PCIumxH3EsHxaVpgor2W1gQs+hkweKy7YDvpncP99GgHHQ5vwHwrqJvw57ng=


branches:
  only:
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"
