language: ruby
rvm:
- 2.4

install:
- bundle install

script: bundle exec rake site:deploy --trace

env:
  global:
    secure:
      FdCMZvUEYA8uZLbDD8asNJWmfTfB0AJ9F5Im2HDFIZ2RUf8trPtq+bWmBTGmIU4APoBrsjdyg87QSRXIJmHC2xFLMoH21DRFLEa2oy9p7qiplR1BCVqNG0ioLOfCuTKXm6DYP0MzY57mnQ/ewTFppO05cN0k1REw4JqmJzaZ1aASEAnOb11IqE08ocliICiuXhasdtW0cNDnYvr57Fh3i2JBzSoLcvHxsSg9ioTw2mPuVLltT0WtP+JyrnjzgwWRrZYOGSKfO4WnzUuZAB+chJ4AnU+/pg05mpCaS6LRqORwEWEvPJRfwxV9X8CfOqwyZK/JpyLvN4CoRG/C513BPNJGUT8GZOYJ0k7b0GBtvAIs3KUkTcjKas/y2uDtuKxaZNFUhbxGcifKNvv/Tljj16ca0jPanc8CKzsBIu4RfaTWnruBiAzV1X66fuaPHvJHAj98wyCsXn+gIIDiVuj5PUOzEEkau0UIeTON4YFnYSAnvQ/JMlJ+hEvwFhwxbpXlkpjAPgtEih4pNYU6OkdvZTAiAB/GiiYdYcszOit7MtvBiB+ZtWP04wM3ZJWimhlwasfvIuU6tAanaAtA0rylEWr2NnVF8Nn2HyCKYv5NzuERgtsu96Y2t2hFrOhY1kWHkq8JuWOEzypGzfebePN+gPaG7HIUKOjTulg/0+YuedI=
      
branches:
  only:
  - master
  - gh-pages
  - /pages-(.*)/ # test every branch which starts with "pages-"
