language: ruby
rvm:
- 2.4

install:
- bundle install

script: bundle exec rake site:deploy --trace

env:
  global:
    secure: nuhSj3ndgQ6yzzIwXF64yhMXIxYuAtHGVJuJ6hAJ9SrqSy1Lcg+L9f2JShEg9cxmZbS/dYANbwH8W1Nr5qaqXzO09rHGZpAEnz+yOZEZNhaKdMeQK08EXkxE6JcV/rw0KuMiML1FhiKTZDqqCx36TC6hRK7PsX9DbaLjSFH798NMx80iVntGisgb9Qm9PseMClIQ+VwPSlqs9suMGK07tx3rn5JIuqg9zLFj3U4G0H2EtQj1c7r9LLS2Hs5z71AE0rnaVrQ5eubCKAlwT1RoOJnwWTKy8UmpZc7xfhjX/lFZc58C3qfMEz8XlQv8GMm74AXZ13gGd2gMYvQamdvwM4X988jQnOSjWAgLbdhDqNmGP4ObO3ZUG7ZQg1qzOjQi1O7caeMdj8oLwt4kjR5dlKrNTjgiHIU24mkTeTJ7/wNXg7qj9IGcsybJSJwjimKBBsQJLRfWogwpMjKG5VBS/1sjgQ3u4KHHsQsApnRrjmoGRYZ1r9WrRiKRLZ2wZuP3o8dw52X4eF7mKyMh8eBX3B/N2RA+gjjgzWDpzap35XvckBowxwRUIQlDx+1R73dcxfc1jlZJOKhaGYrw+z18I8s+OJMjvx0vq7wxYDsBBylL4o00Qs+rKwF5KC4TFHUU6gYaCi2OJukXQMEd7HtmypUUvI4R1rPLEl1o5CeaiJU=

branches:
  only:
  - master
  - /pages-(.*)/ # test every branch which starts with "pages-"
